README.md

Under Table of projects there was a bullet point without any data which was looking odd. So thought of removing that.
Apart from that thought of adding icons to the links provided in the Find us section.
(Done this because you had said to find mistakes like spelling mistakes, etc... 
I hope this isn't silly :) )
I'm a beginner so this might not have met your expectations.

Adding icons to links and cleaning up typos!!

---

index.html

_Note: [First iteration](https://user-images.githubusercontent.com/18630253/91643167-dc124e00-ea28-11ea-84bb-013c1a5cea2c.png)_
_Note: [First iteration](https://user-images.githubusercontent.com/18630253/91643167-dc124e00-ea28-11ea-84bb-013c1a5cea2c.png)_
Closes: #6

feat(moderators): add moderators cards

---

index.html

feat: project cards onClick direct to repo #34

---

CONTRIBUTING.md

Trying to get a feel of pull requests 😄😅

Tweaking the Grammar

---

NEWCOMERS.md

Improving Readability

---

README.md

Fix PR #31 
Update Website Screenshot on README.md

Update Readme.md with Website Screenshot

---

index.html

closes #58 
added "https://" before Amandine Flachs' website link you forgot to put that here that's why website is not opening

added "https://" before Amandine Flachs' website

---

.github/workflows/tests.yml
README.md

Cypress on GitHub Actions

---

.github/workflows/deploy.yml

Closes #71 
Added the `deploy.yml`. 
Could you check if it will deploy correctly `line 25`. Or if I need to change this to be the `src` folder.

feat: added Github deploy action

---

.github/workflows/tests.yml

Added **edited** to the pull request types to re-run the testing. As mentioned in #77 
_Side note: sorry for small pull request. Also see this as a small practice for Hacktoberfest_

feat(testing): added extra type in Github action

---

cypress/integration/homepage.feature

feat(test): Footer links #81

---

src/App.svelte

link image of readme.md to newcomers.md

---

README.md

This PR fixes issue #97  
Update README with note on multiple tech branches and why they are there.

Update README with note on multiple tech branches

---

.github/workflows/alex.yml
README.md

closes #108 
Action "Alex" https://github.com/get-alex/alex

feat: alex action added

---

public/index.html

The site previously did not have any fonts, it was using arial system font coming from tailwind's stylesheet.
I have added two fonts from google fonts
- Archivo (for headings)
- Roboto (For other text)
- Archivo [500, 700]
- Roboto [400, 500 Italic]
500 - Regular Headings
700 - Bold Headings
400 - Everything Else
500 - Emphasizing on text

Added some fonts

---

public/index.html
src/App.svelte

I had added two new fonts in the previous commit but not used them, in this commit i have created a css class called archivo which uses the archivo font and used roboto everywhere else.

Changing Fonts

---

README.md

Adding Discord, GitHub, YouTube badges

---

src/App.svelte

Made some changes to the community web page.
I'm open to any changes 😊.
These are the changes,
```diff
- We believe Open Source is for everyone, yes you!
+ We believe Open Source is for everyone, yes you too!
- OPEN SOURCE is NOT about code, it is about people and collaboration
+ OPEN SOURCE is NOT all about code, it is also the people and collaboration.
- Raise an issue on the support repo asking to join (<a
+ Raise an issue on the support repo requesting to join the community (<a
```

Fixed some grammar issues

---

public/index.html

For more information on how preconnect the improve performance check [here](https://sia.codes/posts/making-google-fonts-faster/#warm-up-that-connection-faster)
This is the only change
```diff
+ <link rel="preconnect" href="https://fonts.gstatic.com">
```
Suggestions are welcomed 😊

Added preconnect to improve performance

---

.github/workflows/lighthouse-check.yml
src/data.js

Close #132 
Close #135 
corrected typo "live Steaming" to "Live streaming"
Changed the Website URL in lighthouse-check.yml

Corrected the typo and changed the Website URl in lighthouse-check.yml

---

.github/workflows/lighthouse-check.yml

Updates lighthouse to use new URL. This will resolve some CI failures on #136 and #133.
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

fix(tools): Update lighthouse

---

public/index.html

Change `Eddie Jaoude` to `EddieHub`

feat: use community name

---

.github/workflows/community.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
NEWCOMERS.md
README.md
package.json
src/App.svelte
src/data.js

closes #142 
Search and replaced old org name for new name

fix: rename org name (#142)

---

src/App.svelte

Hero image removed and replaced with video by @Prathamkrishna in PR #129

feat: community youtube video (#125)

---

src/data.js

* Changed the name to full name.
* Changed the image to new image, matching others.
Here's a Preview:

Updated Praveen's Details.

---

README.md

Closes #128 
Updated the image of the website at README.md, with this [image file](https://user-images.githubusercontent.com/44549418/109976323-a7f24f80-7d21-11eb-8348-393b7ee10a8c.jpg).

fix: updated website image at README.md (#128)

---

package-lock.json
src/data.js

Nicholas Carrigan Added to moderators section

---

README.md

Paraphrasing some lines

---

README.md

Added Community Social Media Badge in README.md

Added Community Social Media Badge

---

CODE_OF_CONDUCT.md

I have updated the email as requested in the issue no [#221](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/220).

Update COC Email

---

README.md

I take all the badges in center

Readme.md File changes in design/.

---

README.md

Updated the word low code => low-code.

---

index.html

added  language to html tag

---

src/components/Hero.jsx

feat: hero text

---

src/components/Faqs.jsx

Migrate FAQs to new template

---

src/components/Header.jsx
src/components/Hero.jsx

feat: navlinks and youtube link

---

src/components/Header.jsx

Feat add blog link

---

src/components/Testimonials.jsx

feat: add my testimonial

---

src/components/SecondaryFeatures.jsx

fix: github collab text

---

.gitpod.yml
README.md

Closes #276 
Add Gitpod support both for development and on PR preview

chore: Add gitpod support

---

src/components/SecondaryFeatures.jsx

fix: overlapping of feature icon

---

package.json
src/app/layout.jsx
src/components/Footer.jsx

Closes #298 
- Added the FontAwesome library to add brand icons
- Added the Twitter and LinkedIn links at the bottom of the page
For now, I've only added the font awesome brand icons to the project. We can add another pack in the future if we need it.

feat: add LinkedIn/Twitter(X)

---

src/app/page.jsx
src/components/Founder.jsx
src/components/Founders.jsx
src/components/InfoSection.jsx
src/components/YouTubeEmbed.jsx

Closes #290 
Hope this works fine. Feel free to give me any feedback. Thanks.

feat: add founder section

---

package-lock.json
package.json
src/app/page.jsx
src/components/Footer.jsx
src/components/ScrollToTop.jsx

feat: add scroll to top button

---

src/components/Faqs.jsx

I was looking for steps to join the `EddiHubCommunity` and realized faq section referring to "this form" which did not help me. This change is to fix the documentation so anyone like me in future has an better response in faq to join the community. 
After the changes here is how the faq will look like 
This is my first PR in open source community, kindly let me know if I missed any steps.

docs: fix faq on how to join EddieHubCommunity github

---

src/components/Footer.jsx

`Closes #310 ` Add Links to Partner Icons : #310
- Added links to the partner icons

[FEATURE] Add Links to Partner Icons 
